# pyright: reportMissingImports=false, reportMissingModuleSource=false
# -*- coding: utf-8 -*-
"""Plant_Diseases_Detection_FineTuned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znHwd2q6Swr4pMWRJcwxWzyvc_jTzo8w
"""

# --- COLAB ENVIRONMENT SETUP ---
try:
    import cv2
    import ipywidgets
except ImportError:
    raise ImportError(
        "Install the project requirements before running this script locally."
    )

#print("✅ Core dependencies ready.")

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
vipoooool_new_plant_diseases_dataset_path = kagglehub.dataset_download('vipoooool/new-plant-diseases-dataset')

print('Data source import complete.')

import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dropout
from keras.applications.vgg16 import VGG16

Root_dir = "/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)"
train_dir = Root_dir + "/train"
valid_dir = Root_dir + "/valid"
test_dir = "/kaggle/input/new-plant-diseases-dataset/test"
Diseases_classes = os.listdir(train_dir)

#from google.colab import drive
#drive.mount('/content/drive')

plant_names = []
Len = []
for i in Diseases_classes:
    plant_names.append(i)
    imgs_path = os.listdir(train_dir + "/" + i)
    Len.append(len(imgs_path))

Len.sort(reverse=True)

sns.set(style="whitegrid", color_codes=True)
plt.figure(figsize=(20,20),dpi=200)
ax = sns.barplot(x= Len, y= plant_names, palette="Greens")
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.show()

# generators - divides data into batches
train_dataset=keras.utils.image_dataset_from_directory(
    directory=train_dir,
    labels='inferred',
    label_mode='int',
    batch_size=32,
    image_size=(256, 256)
)
validation_dataset=keras.utils.image_dataset_from_directory(
    directory=valid_dir,
    labels='inferred',
    label_mode='int',
    batch_size=32,
    image_size=(256, 256)
)

test_dataset=keras.utils.image_dataset_from_directory(
    directory=test_dir,
    labels='inferred',
    label_mode='int',
    batch_size=32,
    image_size=(256, 256)
)

# Normalize
def process(image, label):
  image=tf.cast(image/255. , tf.float32)
  return image,label

train_ds=train_dataset.map(process)
validation_ds=validation_dataset.map(process)
test_ds=test_dataset.map(process)

conv_base = keras.applications.Xception(
    weights='imagenet',  # Load weights pre-trained on ImageNet.
    input_shape=(256, 256, 3),
    include_top=False)  # Do not include the ImageNet classifier at the top.

conv_base.trainable = True

set_trainable = False

for layer in conv_base.layers:
  if layer.name == 'block14_sepconv1':
    set_trainable = True
  if set_trainable:
    layer.trainable = True
  else:
    layer.trainable = False

for layer in conv_base.layers:
  print(layer.name,layer.trainable)

conv_base.summary()

model = Sequential()

model.add(conv_base)
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(len(Diseases_classes),activation='softmax'))



# model=Sequential()
# model.add(Conv2D(32,kernel_size=(3,3),padding='valid',activation='relu',input_shape=(256,256,3)))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

# model.add(Conv2D(64,kernel_size=(3,3),padding='valid',activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

# model.add(Conv2D(128,kernel_size=(3,3),padding='valid',activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

# model.add(Flatten())

# model.add(Dense(128,activation='relu'))
# model.add(Dropout(0.1))
# model.add(Dense(64,activation='relu'))
# model.add(Dropout(0.1))
# model.add(Dense(len(Diseases_classes),activation='softmax'))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.summary()

history=model.fit(train_ds,epochs=10,validation_data=validation_ds)

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'],color='red',label='train')
plt.plot(history.history['val_accuracy'],color='blue',label='validation')
plt.legend()
plt.show()

model.save('plant_disease_model_1.keras')

from tensorflow import keras

loaded_model = keras.models.load_model('plant_disease_model.keras')
print('Model loaded successfully.')

# Make predictions on the test data
predictions = loaded_model.predict(test_ds)

# Get predicted class indices
predicted_classes = np.argmax(predictions, axis=1)

print(f"Predictions made for {len(predicted_classes)} test images.")

# Display some sample predictions
plt.figure(figsize=(20, 10))
for i, (image, true_label) in enumerate(test_ds.unbatch().take(9)):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image.numpy())
    predicted_class_index = predicted_classes[i]
    predicted_disease = Diseases_classes[predicted_class_index]
    true_disease = Diseases_classes[true_label.numpy()]
    plt.title(f"True: {true_disease}\nPredicted: {predicted_disease}")
    plt.axis("off")
plt.show()

"""1. **Validation**: Checks for blur, exposure, and leaf presence.
2. **Threshold**: 80% confidence required for diagnosis.
3. **Treatments**: Detailed advice for all 38 classes.
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

def validate_image_quality(img_path):
    """
    Analyzes image quality for brightness, sharpness, and plant content.
    Returns: (bool, message)
    """
    img = cv2.imread(img_path)
    if img is None: return False, "Invalid image file."

    # 1. Brightness Check
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    brightness = np.mean(gray)
    if brightness < 40: return False, "Image is too dark."
    if brightness > 240: return False, "Image is overexposed."

    # 2. Sharpness Check
    laplacian_var = cv2.Laplacian(gray, cv2.CV_64F).var()
    if laplacian_var < 70: return False, "Image is too blurry. Focus on the leaf."

    # 3. Plant Tone Check (HSV color mask)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    lower = np.array([10, 20, 20])   # Broader range for leaves (Green to Brown)
    upper = np.array([100, 255, 255])
    mask = cv2.inRange(hsv, lower, upper)
    ratio = np.count_nonzero(mask) / (img.shape[0] * img.shape[1])
    if ratio < 0.1: return False, "No plant material detected. Center the leaf."

    return True, "Quality check passed."

TREATMENT_GUIDE = {
    'Apple___Apple_scab': '• Remove fallen leaves to reduce inoculum. • Apply sulfur or copper-based fungicides in early spring. • Improve air circulation through pruning.',
    'Apple___Black_rot': '• Prune out dead wood and cankers during dormancy. • Remove mummified fruit from the tree. • Apply appropriate fungicides from bloom to harvest.',
    'Apple___Cedar_apple_rust': '• Remove nearby juniper/cedar trees if possible. • Apply protective fungicides in early spring. • Plant rust-resistant apple varieties.',
    'Apple___healthy': '• Healthy plant. Maintain regular watering. • Use a balanced fertilizer. • Monitor for early signs of pests.',
    'Blueberry___healthy': '• Healthy plant. Maintain acidic soil (pH 4.5-5.5). • Mulch to retain moisture. • Prune old wood every year.',
    'Cherry_(including_sour)___Powdery_mildew': '• Apply horticultural oil or potassium bicarbonate. • Prune to improve airflow. • Avoid overhead irrigation.',
    'Cherry_(including_sour)___healthy': '• Healthy tree. Ensure adequate spacing. • Monitor for aphids. • Maintain consistent soil moisture.',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': '• Use resistant hybrids. • Rotate crops with non-grasses. • Apply foliar fungicides if disease is severe.',
    'Corn_(maize)___Common_rust_': '• Plant resistant hybrids. • Application of fungicides is rarely needed unless infection is early. • Rotate crops.',
    'Corn_(maize)___Northern_Leaf_Blight': '• Use resistant cultivars. • Manage crop residue through tillage. • Rotate with crops like soybean.',
    'Corn_(maize)___healthy': '• Optimal health. Maintain nitrogen levels. • Scouting for early insect damage. • Ensure good drainage.',
    'Grape___Black_rot': '• Practice meticulous sanitation—remove all old fruit. • Apply fungicides (mancozeb, myclobutanil). • Prune for sunlight and air.',
    'Grape___Esca_(Black_Measles)': '• Proper pruning and wound protection. • Remove and destroy infected wood. • No effective fungicide currently exists for established Esca.',
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': '• Post-harvest fungicide application. • Prune to increase air circulation. • Remove infected debris.',
    'Grape___healthy': '• Healthy vine. Continue balanced fertilizing. • Prune to maintain canopy. • Monitor for mites.',
    'Orange___Haunglongbing_(Citrus_greening)': '• Remove infected trees immediately. • Control citrus psyllid vector with insecticides. • Use psyllid-free nursery stock.',
    'Peach___Bacterial_spot': '• Use resistant varieties. • Apply copper-based sprays in fall/winter. • Avoid excess nitrogen fertilization.',
    'Peach___healthy': '• Healthy tree. Monitor for borers. • Thin fruit to prevent branch breakage. • Prune to an open-center shape.',
    'Pepper,_bell___Bacterial_spot': '• Use disease-free seeds/transplants. • Apply copper-based bactericides. • Rotate crops every 3 years.',
    'Pepper,_bell___healthy': '• Healthy plant. Support with stakes. • Mulch to keep soil moist. • Avoid touching plants when wet.',
    'Potato___Early_blight': '• Use certified seeds. • Rotate with non-solanaceous crops. • Apply fungicides containing chlorothalonil.',
    'Potato___Late_blight': '• Use resistant varieties. • Destroy cull piles and volunteers. • Apply protective fungicides (ridomil) regularly.',
    'Potato___healthy': '• Healthy crop. Maintain even moisture. • Hill up soil around stems. • Monitor for Colorado Potato Beetle.',
    'Raspberry___healthy': '• Healthy patch. Thin canes for air. • Maintain 2-3 inches of mulch. • Prune out old canes after harvest.',
    'Soybean___healthy': '• Healthy crop. Scout for Japanese beetles. • Monitor for soybean rust. • Maintain weed control.',
    'Squash___Powdery_mildew': '• Apply neem oil or sulfur. • Sprout resistant varieties. • Avoid high-nitrogen fertilizers which boost mildew.',
    'Strawberry___Leaf_scorch': '• Renovate beds after harvest. • Remove old foliage. • Apply fungicides if infection is heavy.',
    'Strawberry___healthy': '• Excellent condition. Mulch with straw. • Remove runners to increase yield. • Pick berries promptly.',
    'Tomato___Bacterial_spot': '• Avoid overhead water. • Apply copper fungicides. • Space plants for better air movement.',
    'Tomato___Early_blight': '• Remove lower leaves near ground. • Mulch around base. • Apply fungicides (copper/sulfur) at first sign.',
    'Tomato___Late_blight': '• High risk. Space plants widely. • Apply fungicides early. • Remove and destroy infected plants immediately.',
    'Tomato___Leaf_Mold': '• Increase ventilation. • Keep foliage dry. • Reduce humidity in greenhouse settings.',
    'Tomato___Septoria_leaf_spot': '• Remove infected bottom leaves. • Clean up garden debris in fall. • Use copper or chlorothalonil sprays.',
    'Tomato___Spider_mites Two-spotted_spider_mite': '• Use insecticidal soap or oil. • Blast leaves with water. • Encourage natural predators like ladybugs.',
    'Tomato___Target_Spot': '• Ensure wide spacing. • Prune suckers to improve air. • Use chlorothalonil or mancozeb fungicides.',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': '• Use reflective mulch to deter whiteflies. • Remove weed hosts. • Plant virus-resistant varieties.',
    'Tomato___Tomato_mosaic_virus': '• Do not use tobacco near plants. • Wash hands after handling infected plants. • Remove and burn infected bushes.',
    'Tomato___healthy': '• Vibrant health. Support with cages. • Water consistently at the base. • Prune suckers for better fruit size.'
}
print(" Validation and Treatment Logic Loaded.")

def diagnostic_pipeline(img_path, active_model, classes, threshold=0.8):
    """
    Full diagnostic flow: Quality -> Inference -> Threshold -> Actionable Output
    """
    # 1. Image Quality Check
    is_valid, err_msg = validate_image_quality(img_path)
    if not is_valid:
        print(f" QUALITY WARNING: {err_msg}")
        return

    # 2. Pre-process
    img = image.load_img(img_path, target_size=(256, 256))
    x = image.img_to_array(img) / 255.0
    x = np.expand_dims(x, axis=0)

    # 3. Predict
    preds = active_model.predict(x, verbose=0)
    confidence = np.max(preds)
    cls_idx = np.argmax(preds)
    result_name = classes[cls_idx]

    # 4. Apply Confidence Gate
    plt.imshow(img)
    plt.axis('off')
    if confidence < threshold:
        plt.title(f"Low Confidence ({confidence*100:.1f}%)", color='red')
        print(f" NOT CONFIDENT: Model is only {confidence*100:.1f}% sure that this is {result_name}.")
        print("Please provide a clearer, closer photo of the leaf symptoms.")
    else:
        plt.title(f"{result_name} ({confidence*100:.1f}%)", color='green')
        print(f" DIAGNOSIS: {result_name}")
        print(f" CONFIDENCE: {confidence*100:.1f}%")
        print("\n ACTIONABLE TREATMENTS:")
        treatments = TREATMENT_GUIDE.get(result_name, "- Observe and monitor carefully.")
        for t in treatments.split('•'):
             if t.strip(): print(f"  ✅ {t.strip()}")
    plt.show()

import ipywidgets as widgets
from IPython.display import display, clear_output

uploader = widgets.FileUpload(accept='image/*', multiple=False)
output = widgets.Output()

def on_upload(change):
    with output:
        clear_output()
        if not uploader.value: return

        # Compatibility for ipywidgets v7 and v8
        try:
            file_info = uploader.value[0]
            content = file_info['content']
            fname = file_info['name']
        except:
            fname = list(uploader.value.keys())[0]
            content = uploader.value[fname]['content']

        with open("temp_leaf.jpg", "wb") as f: f.write(content)
        print(f" Scanning {fname}...")

        # Determine model var
        active_model = None
        if 'loaded_model' in globals(): active_model = loaded_model
        elif 'model' in globals(): active_model = model

        if active_model and 'Diseases_classes' in globals():
            diagnostic_pipeline("temp_leaf.jpg", active_model, Diseases_classes)
        else:
            print(" ERROR: Model or class names not found. Run training cells first.")

uploader.observe(on_upload, names='value')
print("--- PLANT DIAGNOSTIC INTERFACE ---")
display(uploader, output)

# Save in the latest Keras format (best for portability)
if 'model' in globals():
    model.save('plant_disease_model.keras')
    print(" Saved trained model as: plant_disease_model.keras")
elif 'loaded_model' in globals():
    loaded_model.save('plant_disease_model.keras')
    print(" Re-saved loaded model as: plant_disease_model.keras")
else:
    print(" No model found in memory to save.")
